## Question 1
### (A)

In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

In [56]:
#importing data
dataset = pd.read_csv('datasets\CC.csv')

In [57]:
dataset.head()

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,C10001,40.900749,0.818182,95.40,0.00,95.4,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12
1,C10002,3202.467416,0.909091,0.00,0.00,0.0,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12
2,C10003,2495.148862,1.000000,773.17,773.17,0.0,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,NaN,0.000000,12
4,C10005,817.714335,1.000000,16.00,16.00,0.0,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12

In [58]:
print(dataset.shape)

(8950, 18)

In [20]:
#droping the unwanted data
dataset = dataset.drop("CUST_ID", axis=1)

In [21]:
#checking for Null values
dataset.isnull().sum()

BALANCE                               0
BALANCE_FREQUENCY                     0
PURCHASES                             0
ONEOFF_PURCHASES                      0
INSTALLMENTS_PURCHASES                0
CASH_ADVANCE                          0
PURCHASES_FREQUENCY                   0
ONEOFF_PURCHASES_FREQUENCY            0
PURCHASES_INSTALLMENTS_FREQUENCY      0
CASH_ADVANCE_FREQUENCY                0
CASH_ADVANCE_TRX                      0
PURCHASES_TRX                         0
CREDIT_LIMIT                          1
PAYMENTS                              0
MINIMUM_PAYMENTS                    313
PRC_FULL_PAYMENT                      0
TENURE                                0
dtype: int64

In [22]:
#filling null values with mean values
dataset = dataset.fillna(dataset.mean())
dataset.isnull().sum()

BALANCE                             0
BALANCE_FREQUENCY                   0
PURCHASES                           0
ONEOFF_PURCHASES                    0
INSTALLMENTS_PURCHASES              0
CASH_ADVANCE                        0
PURCHASES_FREQUENCY                 0
ONEOFF_PURCHASES_FREQUENCY          0
PURCHASES_INSTALLMENTS_FREQUENCY    0
CASH_ADVANCE_FREQUENCY              0
CASH_ADVANCE_TRX                    0
PURCHASES_TRX                       0
CREDIT_LIMIT                        0
PAYMENTS                            0
MINIMUM_PAYMENTS                    0
PRC_FULL_PAYMENT                    0
TENURE                              0
dtype: int64

In [23]:
pca = PCA(2)#applying PCA and took K(components)=2
pca.fit(dataset)

PCA(n_components=2)

In [24]:
x_pca = pca.fit_transform(dataset)
df = pd.DataFrame(data=x_pca)

In [25]:
print(df)

                0            1
0    -4326.383956   921.566884
1     4118.916676 -2432.846347
2     1497.907660 -1997.578692
3     1394.548556 -1488.743450
4    -3743.351874   757.342659
...           ...          ...
8945 -4208.357938  1122.443274
8946 -4123.924001   951.683803
8947 -4379.444202   911.504566
8948 -4791.117744  1032.540944
8949 -3623.702749  1555.134769

[8950 rows x 2 columns]

## Question 1
### (B)

In [26]:
#Doing K-means after PCA
nclusters = 3           # this is the k in kmeans
km = KMeans(n_clusters=nclusters)
km.fit(df)

KMeans(n_clusters=3)

In [13]:
# predict the cluster for each data point
y_cluster_kmeans = km.predict(df)
from sklearn import metrics
score = metrics.silhouette_score(df, y_cluster_kmeans)
print(score)

0.572039304887005

## Question 1
### (C)

In [14]:
#Doing feature scaling for main dataset
scaler = StandardScaler()
X_Scale = scaler.fit_transform(dataset)

In [15]:
#Applying PCA after feature scaling into original dataset
pca = PCA(2)#applying PCA and took K(components)=2
x_pca = pca.fit_transform(X_Scale)

In [16]:
#Doing K-means after scaling+PCA
nclusters = 3           # this is the k in kmeans
km = KMeans(n_clusters=nclusters)
km.fit(x_pca)

KMeans(n_clusters=3)

In [17]:
# predict the cluster for each data point
y_cluster_kmeans = km.predict(x_pca)
from sklearn import metrics
score = metrics.silhouette_score(x_pca, y_cluster_kmeans)
print(score)

0.4517172500815408

In [ ]:
# silhouette score is decreasing after doing feature scaling

## Question 2
### (A)

In [36]:
#importing dataset
dataset = pd.read_csv('datasets\pd_speech_features.csv')
dataset.head()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

In [38]:
from sklearn import preprocessing

#Performing feature scaling on dataset
scaler = preprocessing.StandardScaler()
scaler.fit(dataset)
dataset.head()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

## Question 2
### (B)

In [43]:
X = dataset.drop('class',axis=1).values
y = dataset['class'].values

#Applying PCA k=3 on dataset
pca2 = PCA(n_components=3)
principalComponents = pca2.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2','principal component 3'])
finalDf = pd.concat([principalDf, dataset[['class']]], axis = 1)
finalDf.head()

   principal component 1  principal component 2  principal component 3  class
0          -5.815816e+09           4.701391e+06          -6.210264e+05      1
1          -6.029399e+09           4.610122e+06          -4.198081e+05      1
2          -6.159184e+09           5.578720e+06          -4.115108e+05      1
3          -7.197145e+09           5.943199e+07           1.355807e+06      1
4          -6.423357e+09           8.714129e+07           1.791626e+07      1

## Question 2
### (C)

In [42]:
from sklearn.model_selection import train_test_split

#Spliting data for testing and training
X = finalDf.drop('class',axis=1).values
y = finalDf['class'].values
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=0)

# import SVC classifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
# instantiate classifier with default hyperparameters
svc=SVC() 
# fit classifier to training set
svc.fit(X_train,y_train)
# make predictions on test set
y_pred=svc.predict(X_test)

# computing and print accuracy score
accuracy = accuracy_score(y_test,y_pred)*100
print("accuracy of SVM:",accuracy)

accuracy of SVM: 75.77092511013215

## Question 3

In [47]:
#importing dataset
dataset = pd.read_csv('datasets\Iris.csv')
dataset.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [51]:
#Encoding target column
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(dataset["Species"].values)

x = dataset.iloc[:,range(0,4)].values

#implementation of LDA with k = 2 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=2)
X_train_lda = lda.fit_transform(x, y)

#Displaying result of LDA with k=2
data=pd.DataFrame(X_train_lda)
data['class']=y
data.columns=["LD1","LD2","class"]
data.head()

        LD1       LD2  class
0  9.423452 -0.513976      0
1  8.751900 -1.591678      0
2  8.973004 -1.068204      0
3  8.170186 -1.435135      0
4  9.249789 -0.136869      0

In [52]:
#implementation of PCA with k = 2 
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)

principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])

finalDf = pd.concat([principalDf, data[['class']]], axis = 1)
finalDf.head()

   principal component 1  principal component 2  class
0              74.541053               0.408042      0
1              73.542545               0.274103      0
2              72.550398               0.043474      0
3              71.544942               0.125560      0
4              70.545790               0.203177      0

## Question 4

In [54]:
#difference between LDA and PCA
#LDA is useful when we have labels for data points and want to predict which label new points will have based on their 
#values. while if we don’t have labels then PCA will be useful.
#LDA is used for classification and PCA is used to get  low dimensional data.